version: '3.8'

volumes:
  postgres_data:
  static_volume:
  nginx:

services:
  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: cementhools/yamdb_final:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - nginx:/code/nginx/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - static_volume:/static/
      - nginx:/etc/nginx/conf.d/
    ports:
      - 8080:80
    depends_on:
      - web



