version: '3.8'

volumes:
  postgres_data:
  static_volume:
  nginx:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: cementhools/yamdb:latest
    restart: always
    volumes:
      - static_volume:/static/
      - nginx:/nginx/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/static/
      - nginx:/etc/nginx/conf.d/
    ports:
      - 8000:80
    depends_on:
      - web



