version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_volume:code/static/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:code/static/
    ports:
      - 8000:80
    depends_on:
      - web

  volumes:
    postgres_data:
    static_volume:
