# Generated by Django 3.0.5 on 2020-11-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_auto_20201117_1942'),
        ('auth_user', '0002_auto_20201116_1824'),
    ]

    operations = [
    ]
