# Generated by Django 3.0.5 on 2020-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_auto_20201118_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
