# Generated by Django 3.0.5 on 2020-11-23 11:43

from django.db import migrations, models
import title.validators


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0004_auto_20201122_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[title.validators.year_validate], verbose_name='год выхода'),
        ),
    ]
